language: python
python:
  - "3.8.3"
  - "nightly"

  # command to install dependencies
  install:
    - "pip install pytest"
    - "pip install -r requirements.txt"

  # command to run tests
  script: python -m pytest unit10